-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."chat_rooms" add column "is_public" boolean
--  null default 'false';
